"""
SkillLibrary — Persistent skill storage and retrieval.

Saves agent-generated tools as Python files on disk,
indexes them by name/description, and retrieves by
keyword similarity for reuse in future tasks.

Inspired by Voyager (NeurIPS 2023) skill library.

Example:
    lib = SkillLibrary("~/.jadeagent/skills")
    lib.save("reverse_str", code, "Reverse a string")
    tools = lib.search("reverse text")  # → [Tool(reverse_str)]
"""

from __future__ import annotations

import importlib.util
import json
import logging
import os
import re
from pathlib import Path
from typing import Any

from ..core.tools import Tool
from ..core.types import ToolSchema

logger = logging.getLogger("jadeagent.skills")

# Default skill storage path
DEFAULT_SKILLS_DIR = os.path.expanduser("~/.jadeagent/skills")
INDEX_FILE = "skills_index.json"


class SkillLibrary:
    """
    Persistent library of agent-generated tools.

    Skills are saved as individual .py files with a JSON index
    for fast retrieval by keyword/description matching.

    Args:
        path: Directory to store skill files. Created if missing.

    Example:
        lib = SkillLibrary()

        # Save a skill
        code = '''
        def reverse_string(text: str) -> str:
            \"\"\"Reverse the input text.\"\"\"
            return text[::-1]
        '''
        lib.save("reverse_string", code, "Reverse a string")

        # Retrieve later
        tools = lib.search("reverse text")
        result = tools[0].execute({"text": "hello"})  # → "olleh"
    """

    def __init__(self, path: str | None = None):
        self.path = Path(path or DEFAULT_SKILLS_DIR).expanduser()
        self.path.mkdir(parents=True, exist_ok=True)
        self._index: dict[str, dict] = {}
        self._load_index()

    def _index_path(self) -> Path:
        return self.path / INDEX_FILE

    def _load_index(self):
        """Load the skill index from disk."""
        idx_path = self._index_path()
        if idx_path.exists():
            try:
                self._index = json.loads(idx_path.read_text(encoding="utf-8"))
                logger.info(f"Loaded {len(self._index)} skills from index")
            except (json.JSONDecodeError, OSError) as e:
                logger.warning(f"Failed to load skill index: {e}")
                self._index = {}
        else:
            self._index = {}

    def _save_index(self):
        """Persist the skill index to disk."""
        self._index_path().write_text(
            json.dumps(self._index, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

    def save(
        self,
        name: str,
        code: str,
        description: str,
        parameters: dict | None = None,
        overwrite: bool = False,
    ) -> Tool:
        """
        Save a skill to the library.

        Args:
            name: Unique skill/function name (e.g. 'download_arxiv').
            code: Python source code containing the function definition.
            description: Human-readable description of what the skill does.
            parameters: Optional JSON schema for the function parameters.
            overwrite: If True, overwrite existing skill with same name.

        Returns:
            Tool object ready for use.

        Raises:
            ValueError: If skill already exists and overwrite=False.
            RuntimeError: If code validation fails.
        """
        if name in self._index and not overwrite:
            raise ValueError(
                f"Skill '{name}' already exists. Use overwrite=True to replace."
            )

        # Validate the code compiles
        try:
            compile(code, f"<skill:{name}>", "exec")
        except SyntaxError as e:
            raise RuntimeError(f"Skill code has syntax error: {e}")

        # Write the .py file
        skill_file = self.path / f"{name}.py"
        header = f'"""{description}\n\nGenerated by JadeAgent SkillGenerator.\n"""\n\n'

        # Don't duplicate header if code already has docstring
        if code.strip().startswith('"""') or code.strip().startswith("'''"):
            full_code = code
        else:
            full_code = header + code

        skill_file.write_text(full_code, encoding="utf-8")

        # Update index
        self._index[name] = {
            "name": name,
            "description": description,
            "file": f"{name}.py",
            "parameters": parameters or {},
        }
        self._save_index()

        logger.info(f"Saved skill: {name}")

        # Return as Tool
        return self._load_skill(name)

    def _load_skill(self, name: str) -> Tool:
        """Load a single skill from disk and return as Tool."""
        if name not in self._index:
            raise KeyError(f"Skill '{name}' not found in index")

        info = self._index[name]
        skill_file = self.path / info["file"]

        if not skill_file.exists():
            raise FileNotFoundError(f"Skill file not found: {skill_file}")

        # Dynamically import the module
        spec = importlib.util.spec_from_file_location(
            f"jadeagent_skill_{name}", str(skill_file)
        )
        module = importlib.util.module_from_spec(spec)

        try:
            spec.loader.exec_module(module)
        except Exception as e:
            raise RuntimeError(f"Failed to load skill '{name}': {e}")

        # Find the function in the module
        func = getattr(module, name, None)
        if func is None:
            # Try to find any callable
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if callable(attr) and not attr_name.startswith("_"):
                    func = attr
                    break

        if func is None:
            raise RuntimeError(
                f"No callable function found in skill '{name}'"
            )

        return Tool(func, name=name, description=info["description"])

    def get(self, name: str) -> Tool | None:
        """Get a specific skill by name."""
        try:
            return self._load_skill(name)
        except (KeyError, FileNotFoundError, RuntimeError) as e:
            logger.warning(f"Failed to get skill '{name}': {e}")
            return None

    def search(self, query: str, top_k: int = 5) -> list[Tool]:
        """
        Search for skills matching a query.

        Uses keyword overlap scoring on skill names and descriptions.
        Returns up to top_k matching tools, sorted by relevance.

        Args:
            query: Natural language description of needed skill.
            top_k: Maximum number of results.

        Returns:
            List of matching Tool objects.
        """
        if not self._index:
            return []

        query_words = set(self._normalize(query).split())
        scored = []

        for name, info in self._index.items():
            # Score by keyword overlap
            desc_words = set(self._normalize(info["description"]).split())
            name_words = set(self._normalize(name).split("_"))

            # Name match is worth more
            name_overlap = len(query_words & name_words)
            desc_overlap = len(query_words & desc_words)
            score = name_overlap * 3 + desc_overlap

            if score > 0:
                scored.append((score, name))

        # Sort by score descending
        scored.sort(reverse=True)

        tools = []
        for _, name in scored[:top_k]:
            tool = self.get(name)
            if tool:
                tools.append(tool)

        return tools

    @staticmethod
    def _normalize(text: str) -> str:
        """Normalize text for keyword matching."""
        text = text.lower()
        text = re.sub(r"[^a-z0-9\s]", " ", text)
        return " ".join(text.split())

    def list_skills(self) -> list[dict]:
        """List all skills in the library."""
        return [
            {"name": name, "description": info["description"]}
            for name, info in self._index.items()
        ]

    def all_tools(self) -> list[Tool]:
        """Load and return all skills as Tools."""
        tools = []
        for name in self._index:
            tool = self.get(name)
            if tool:
                tools.append(tool)
        return tools

    def remove(self, name: str):
        """Remove a skill from the library."""
        if name in self._index:
            skill_file = self.path / self._index[name]["file"]
            if skill_file.exists():
                skill_file.unlink()
            del self._index[name]
            self._save_index()
            logger.info(f"Removed skill: {name}")

    def __len__(self) -> int:
        return len(self._index)

    def __contains__(self, name: str) -> bool:
        return name in self._index

    def __repr__(self) -> str:
        return f"<SkillLibrary(path={self.path}, skills={len(self)})>"
